### ISSUE TITLE
Demo does not work on Chrome / Win

### ISSUE THREAD

**Issue by politbuero-kampagnen** [chrisbolin/offline#4]
Your Demo @ https://chris.bolin.co/offline/ does **not** work for me with the **chrome browser**. In the M$ Edge Browser it **does** work like a charm, however (i.e. I know how to turn on/off Network Connections ;-) ).

My config:
Chrome Version 62.0.3202.94 (Offizieller Build) (64-Bit)
Windows 10 Version 1709 for x64

**Comment by chrisbolin** [comment]
You are very right! I'm so sorry about that. There is actually a bug filed with Chromium about this. I'm working on a backup tho :)

**Comment by chrisbolin** [comment]
closed with https://github.com/chrisbolin/offline/commit/cacb5ebfbf04a0f9eadd902bbdb5c91f1fe4277f (5 years ago)
