### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by thimo1** [chrisbolin/offline#5]
Hi, 

it doesn't seem to work with react 16, following error rises:

`enabled: unsupportedUserAgentsPattern.test(navigator.userAgent),
                                             ^
ReferenceError: navigator is not defined`

<img width="568" alt="bildschirmfoto 2018-06-05 um 10 00 21" src="https://user-images.githubusercontent.com/20241082/40962983-6ce7cb9a-68a7-11e8-9b1b-3267004c1670.png">

Any hint appreciated.

**Comment by chrisbolin** [comment]
hey @thimo1! thanks for reporting this. could you make an issue on https://github.com/chrisbolin/react-detect-offline ? this repository isn't the library `react-detect-offline`, it's the website https://bolin.co/offline

**Comment by chrisbolin** [comment]
on your new issue, could you talk about what command you're running? `navigator` cannot be found, so it's likely running in a non-browser environment, maybe the cjs loader
